In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data  = "ipl_matches_data.xlsx"
Ipl_Century = "ipl_centuries.xlsx"
Team_Data = "teams_data.xlsx"
Player_Data = "players-data-updated.xlsx"

In [ ]:
# ==========================
# Data 1  ipl_matches_data
# ==========================

df = pd.read_excel(data)
df.head()

,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,overs,...,toss_winner,team1,team2,toss_decision,match_winner,win_by_runs,win_by_wickets,player_of_match,result,stage
0,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,20,...,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,field,Kolkata Knight Riders,140.0,NaN,46.0,win,NaN
1,2008,6,Chandigarh,2008-04-19,Indian Premier League,2.0,male,T20,T20,20,...,Chennai Super Kings,Punjab Kings,Chennai Super Kings,bat,Chennai Super Kings,33.0,NaN,11943.0,win,NaN
2,2008,6,Delhi,2008-04-19,Indian Premier League,3.0,male,T20,T20,20,...,Rajasthan Royals,Delhi Capitals,Rajasthan Royals,bat,Delhi Capitals,NaN,9.0,11982.0,win,NaN
3,2008,6,Mumbai,2008-04-20,Indian Premier League,5.0,male,T20,T20,20,...,Mumbai Indians,Mumbai Indians,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,NaN,5.0,11935.0,win,NaN
4,2008,6,Kolkata,2008-04-20,Indian Premier League,4.0,male,T20,T20,20,...,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,NaN,5.0,11922.0,win,NaN

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving ball_by_ball_data.xlsx to ball_by_ball_data.xlsx
Saving data.xlsx to data.xlsx
Saving ipl_centuries.xlsx to ipl_centuries.xlsx
Saving ipl_matches_data.xlsx to ipl_matches_data.xlsx
Saving players-data-updated.xlsx to players-data-updated.xlsx
Saving teams_data.xlsx to teams_data.xlsx

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1169 entries, 0 to 1168
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   season_id        1169 non-null   int64
 1   balls_per_over   1169 non-null   int64
 2   city             1118 non-null   str
 3   match_date       1169 non-null   datetime64[us]
 4   event_name       1169 non-null   str
 5   match_number     1099 non-null   float64
 6   gender           1169 non-null   str
 7   match_type       1169 non-null   str
 8   format           1169 non-null   str
 9   overs            1169 non-null   int64
 10  season           1169 non-null   object
 11  team_type        1169 non-null   str
 12  venue            1169 non-null   str
 13  toss_winner      1168 non-null   str
 14  team1            1169 non-null   str
 15  team2            1169 non-null   str
 16  toss_decision    1168 non-null   str
 17  match_winner     1161 non-null   str
 18  win_by_runs      531 non-null    float64
 19  win_by_wickets   615 non-null    float64
 20  player_of_match  1161 non-null   float64
 21  result           1169 non-null   str
 22  stage            4 non-null      str
dtypes: datetime64[us](1), float64(4), int64(3), object(1), str(14)
memory usage: 141.6+ KB

In [ ]:
df.describe()

,season_id,balls_per_over,match_date,match_number,overs,win_by_runs,win_by_wickets,player_of_match
count,1169.000000,1169.0,1169,1099.000000,1169.0,531.000000,615.000000,1161.000000
mean,2016.687767,6.0,2017-01-15 13:04:40.239521,31.705187,20.0,30.295669,6.200000,3274.304048
min,2008.000000,6.0,2008-04-18 00:00:00,1.000000,20.0,1.000000,1.000000,1.000000
25%,2012.000000,6.0,2012-05-05 00:00:00,16.000000,20.0,11.000000,5.000000,47.000000
50%,2017.000000,6.0,2017-04-10 00:00:00,31.000000,20.0,22.000000,6.000000,318.000000
75%,2022.000000,6.0,2022-03-26 00:00:00,47.000000,20.0,41.000000,7.500000,4047.000000
max,2025.000000,6.0,2025-06-03 00:00:00,72.000000,20.0,146.000000,10.000000,42566.000000
std,5.253100,0.0,NaN,18.518304,0.0,26.866707,1.852193,5857.156934

In [ ]:
df.tail()

,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,overs,...,toss_winner,team1,team2,toss_decision,match_winner,win_by_runs,win_by_wickets,player_of_match,result,stage
1164,2025,6,New Chandigarh,2025-05-30,Indian Premier League,NaN,male,Eliminator,T20,20,...,Mumbai Indians,Mumbai Indians,Gujarat Titans,bat,Mumbai Indians,20.0,NaN,25.0,win,Eliminator
1165,2025,6,Ahmedabad,2025-06-01,Indian Premier League,NaN,male,Qualifier 2,T20,20,...,Punjab Kings,Mumbai Indians,Punjab Kings,field,Punjab Kings,NaN,5.0,389.0,win,Qualifier 2
1166,2025,6,Ahmedabad,2025-06-03,Indian Premier League,NaN,male,Final,T20,20,...,Punjab Kings,Royal Challengers Bangalore,Punjab Kings,field,Royal Challengers Bangalore,6.0,NaN,28.0,win,Final
1167,2025,6,Jaipur,2025-05-24,Indian Premier League,66.0,male,T20,T20,20,...,Delhi Capitals,Punjab Kings,Delhi Capitals,field,Delhi Capitals,NaN,6.0,10070.0,win,NaN
1168,2025,6,Bengaluru,2025-05-17,Indian Premier League,71.0,male,T20,T20,20,...,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,NaN,NaN,NaN,NaN,NaN,no result,NaN

In [ ]:
print(df.columns)

Index(['season_id', 'balls_per_over', 'city', 'match_date', 'event_name',
       'match_number', 'gender', 'match_type', 'format', 'overs', 'season',
       'team_type', 'venue', 'toss_winner', 'team1', 'team2', 'toss_decision',
       'match_winner', 'win_by_runs', 'win_by_wickets', 'player_of_match',
       'result', 'stage'],
      dtype='str')

In [ ]:
df.shape

(1169, 23)

In [ ]:
df.isnull()

,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,overs,...,toss_winner,team1,team2,toss_decision,match_winner,win_by_runs,win_by_wickets,player_of_match,result,stage
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1164,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
1165,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1166,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
1167,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
1168,False,False,False,False,False,False,False,False,False,False,...,True,False,False,True,True,True,True,True,False,True

In [ ]:
df.isnull().sum()

season_id             0
balls_per_over        0
city                 51
match_date            0
event_name            0
match_number         70
gender                0
match_type            0
format                0
overs                 0
season                0
team_type             0
venue                 0
toss_winner           1
team1                 0
team2                 0
toss_decision         1
match_winner          8
win_by_runs         638
win_by_wickets      554
player_of_match       8
result                0
stage              1165
dtype: int64

In [ ]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1164    False
1165    False
1166    False
1167    False
1168    False
Length: 1169, dtype: bool

In [ ]:
df.dropna()

Empty DataFrame
Columns: [season_id, balls_per_over, city, match_date, event_name, match_number, gender, match_type, format, overs, season, team_type, venue, toss_winner, team1, team2, toss_decision, match_winner, win_by_runs, win_by_wickets, player_of_match, result, stage]
Index: []

[0 rows x 23 columns]

In [ ]:
df.fillna(0)

,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,overs,...,toss_winner,team1,team2,toss_decision,match_winner,win_by_runs,win_by_wickets,player_of_match,result,stage
0,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,20,...,Royal Challengers Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,field,Kolkata Knight Riders,140.0,0.0,46.0,win,0
1,2008,6,Chandigarh,2008-04-19,Indian Premier League,2.0,male,T20,T20,20,...,Chennai Super Kings,Punjab Kings,Chennai Super Kings,bat,Chennai Super Kings,33.0,0.0,11943.0,win,0
2,2008,6,Delhi,2008-04-19,Indian Premier League,3.0,male,T20,T20,20,...,Rajasthan Royals,Delhi Capitals,Rajasthan Royals,bat,Delhi Capitals,0.0,9.0,11982.0,win,0
3,2008,6,Mumbai,2008-04-20,Indian Premier League,5.0,male,T20,T20,20,...,Mumbai Indians,Mumbai Indians,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,0.0,5.0,11935.0,win,0
4,2008,6,Kolkata,2008-04-20,Indian Premier League,4.0,male,T20,T20,20,...,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,0.0,5.0,11922.0,win,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1164,2025,6,New Chandigarh,2025-05-30,Indian Premier League,0.0,male,Eliminator,T20,20,...,Mumbai Indians,Mumbai Indians,Gujarat Titans,bat,Mumbai Indians,20.0,0.0,25.0,win,Eliminator
1165,2025,6,Ahmedabad,2025-06-01,Indian Premier League,0.0,male,Qualifier 2,T20,20,...,Punjab Kings,Mumbai Indians,Punjab Kings,field,Punjab Kings,0.0,5.0,389.0,win,Qualifier 2
1166,2025,6,Ahmedabad,2025-06-03,Indian Premier League,0.0,male,Final,T20,20,...,Punjab Kings,Royal Challengers Bangalore,Punjab Kings,field,Royal Challengers Bangalore,6.0,0.0,28.0,win,Final
1167,2025,6,Jaipur,2025-05-24,Indian Premier League,66.0,male,T20,T20,20,...,Delhi Capitals,Punjab Kings,Delhi Capitals,field,Delhi Capitals,0.0,6.0,10070.0,win,0
1168,2025,6,Bengaluru,2025-05-17,Indian Premier League,71.0,male,T20,T20,20,...,0,Royal Challengers Bangalore,Kolkata Knight Riders,0,0,0.0,0.0,0.0,no result,0

In [ ]:
# Before replacing
print("AVG. Wins By Runs")
print(int(df['win_by_runs'].mean()))

print("AVG. Wins By Wickets")
print(int(df['win_by_wickets'].mean()))

AVG. Wins By Runs
30
AVG. Wins By Wickets
6

In [ ]:
#fill 0's
df['win_by_runs'] = df['win_by_runs'].replace(0, df['win_by_runs'].mean())

df['win_by_wickets']= df['win_by_wickets'].replace(0, df['win_by_wickets'].mean())

In [ ]:
# After replacing

print("AVG. Wins By Runs")
print(int(df['win_by_runs'].mean()))

print("AVG. Wins By Wickets")
print(int(df['win_by_wickets'].mean()))

AVG. Wins By Runs
30
AVG. Wins By Wickets
6

In [ ]:
# ==========================
# Data 2  Ipl_Century = "ipl_centuries.xlsx"
# ==========================

df = pd.read_excel(Ipl_Century)
df.head()

,No,Score,Balls,Strike Rate,Player,Team,Opposition,Innings,Venue,City,Date,Result
0,1,158*,73,216.43,Brendon McCullum,Kolkata Knight Riders,Royal Challengers Bangalore,1,M. Chinnaswamy Stadium,Bangalore,2008-04-18,Won
1,2,116*,54,214.81,Michael Hussey,Chennai Super Kings,Kings XI Punjab,1,PCA Stadium,Mohali,2008-04-19,Won
2,3,117*,53,220.75,Andrew Symonds,Deccan Chargers,Rajasthan Royals,1,Rajiv Gandhi International Cricket Stadium,Hyderabad,2008-04-24,Lost
3,4,109*,47,231.91,Adam Gilchrist,Deccan Chargers,Mumbai Indians,2,Wankhede Stadium,Mumbai,2008-04-27,Won
4,5,114*,48,237.50,Sanath Jayasuriya,Mumbai Indians,Chennai Super Kings,2,Wankhede Stadium,Mumbai,2008-05-14,Won

In [ ]:
df.tail()

,No,Score,Balls,Strike Rate,Player,Team,Opposition,Innings,Venue,City,Date,Result
103,104,141,55,256.36,Abhishek Sharma,Sunrisers Hyderabad,Punjab Kings,2,Rajiv Gandhi International Cricket Stadium,Hyderabad,2025-04-12,Won
104,105,101,38,265.78,Vaibhav Suryavanshi,Rajasthan Royals,Gujarat Titans,2,Sawai Mansingh Stadium,Jaipur,2025-04-28,Won
105,106,112*,65,172.30,KL Rahul,Delhi Capitals,Gujarat Titans,1,Arun Jaitley Cricket Stadium,Delhi,2025-05-18,Lost
106,107,108*,61,177.04,Sai Sudharsan,Gujarat Titans,Delhi Capitals,2,Arun Jaitley Cricket Stadium,Delhi,2025-05-18,Won
107,108,117,64,182.81,Mitchell Marsh,Lucknow Super Giants,Gujarat Titans,1,Narendra Modi Stadium,Ahmedabad,2025-05-22,Won

In [ ]:
df.columns

Index(['team_id', 'team_name', 'team_name_short', 'image_url'], dtype='str')

In [ ]:
df.shape

(16, 4)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   No           108 non-null    int64
 1   Score        108 non-null    object
 2   Balls        108 non-null    int64
 3   Strike Rate  108 non-null    float64
 4   Player       108 non-null    str
 5   Team         108 non-null    str
 6   Opposition   108 non-null    str
 7   Innings      108 non-null    int64
 8   Venue        108 non-null    str
 9   City         108 non-null    str
 10  Date         108 non-null    datetime64[us]
 11  Result       108 non-null    str
dtypes: datetime64[us](1), float64(1), int64(3), object(1), str(6)
memory usage: 7.2+ KB

In [ ]:
df.describe()

              No       Balls  Strike Rate     Innings                 Date
count  108.00000  108.000000   108.000000  108.000000                  108
mean    54.50000   57.564815   193.671296    1.324074  2018-05-14 23:46:40
min      1.00000   37.000000   147.050000    1.000000  2008-04-18 00:00:00
25%     27.75000   54.000000   172.410000    1.000000  2013-05-05 00:00:00
50%     54.50000   58.000000   188.985000    1.000000  2019-03-31 00:00:00
75%     81.25000   63.000000   210.235000    2.000000  2023-05-15 18:00:00
max    108.00000   73.000000   270.270000    2.000000  2025-05-22 00:00:00
std     31.32092    7.236038    28.050840    0.470210                  NaN

In [ ]:
df.isnull()

,No,Score,Balls,Strike Rate,Player,Team,Opposition,Innings,Venue,City,Date,Result
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
103,False,False,False,False,False,False,False,False,False,False,False,False
104,False,False,False,False,False,False,False,False,False,False,False,False
105,False,False,False,False,False,False,False,False,False,False,False,False
106,False,False,False,False,False,False,False,False,False,False,False,False
107,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

No             0
Score          0
Balls          0
Strike Rate    0
Player         0
Team           0
Opposition     0
Innings        0
Venue          0
City           0
Date           0
Result         0
dtype: int64

In [ ]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
103    False
104    False
105    False
106    False
107    False
Length: 108, dtype: bool

In [ ]:
print(df.duplicated().sum())

0

In [ ]:
print("Avg. Balls Taken to Score Cenntury: ", int(df['Balls'].mean()) )
print()

print("Max. Balls Taken to Score Cenntury: ",int(df['Balls'].max()) )
print()

print("min. Balls Taken to Score Cenntury: ",int(df['Balls'].min()) )
print()

print("Avg. Strike Rate: " , int(df['Strike Rate'].mean()) )
print()

print("max Strike Rate: " , int(df['Strike Rate'].max()) )
print()

print("min Strike Rate: " , int(df['Strike Rate'].min()))
print()

Avg. Balls Taken to Score Cenntury:  57

Max. Balls Taken to Score Cenntury:  73

min. Balls Taken to Score Cenntury:  37

Avg. Strike Rate:  193

max Strike Rate:  270

min Strike Rate:  147

In [ ]:
# ==========================
# Data 3  Team_Data = "teams_data"
# ==========================

df = pd.read_excel(Team_Data)
df.head()

,team_id,team_name,team_name_short,image_url
0,1,Royal Challengers Bangalore,RCB,https://documents.iplt20.com/ipl/RCB/Logos/Log...
1,2,Sunrisers Hyderabad,SRH,https://documents.iplt20.com/ipl/SRH/Logos/Log...
2,3,Mumbai Indians,MI,https://documents.iplt20.com/ipl/MI/Logos/Logo...
3,4,Rising Pune Supergiant,RPS,https://ipl-stats-sports-mechanic.s3.ap-south-...
4,5,Gujarat Lions,GL,https://ipl-stats-sports-mechanic.s3.ap-south-...

In [ ]:
df.tail()

,team_id,team_name,team_name_short,image_url
11,615,Gujarat Titans,GT,https://documents.iplt20.com/ipl/GT/Logos/Logo...
12,1068,Deccan Chargers,DEC,https://ipl-stats-sports-mechanic.s3.ap-south-...
13,1414,Kochi Tuskers Kerala,KTK,https://ipl-stats-sports-mechanic.s3.ap-south-...
14,1419,Pune Warriors,PWI,https://ipl-stats-sports-mechanic.s3.ap-south-...
15,3604,Rising Pune Supergiants,RPS,https://ipl-stats-sports-mechanic.s3.ap-south-...

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   team_id          16 non-null     int64
 1   team_name        16 non-null     str
 2   team_name_short  16 non-null     str
 3   image_url        16 non-null     str
dtypes: int64(1), str(3)
memory usage: 392.0 bytes

In [ ]:
df.shape

(16, 4)

In [ ]:
df.columns

Index(['team_id', 'team_name', 'team_name_short', 'image_url'], dtype='str')

In [ ]:
df.describe()

          team_id
count    16.00000
mean    610.25000
std     940.96989
min       1.00000
25%       4.75000
50%     193.00000
75%     728.25000
max    3604.00000

In [ ]:
df.isnull()

    team_id  team_name  team_name_short  image_url
0     False      False            False      False
1     False      False            False      False
2     False      False            False      False
3     False      False            False      False
4     False      False            False      False
5     False      False            False      False
6     False      False            False      False
7     False      False            False      False
8     False      False            False      False
9     False      False            False      False
10    False      False            False      False
11    False      False            False      False
12    False      False            False      False
13    False      False            False      False
14    False      False            False      False
15    False      False            False      False

In [ ]:
df.isnull().sum()

team_id            0
team_name          0
team_name_short    0
image_url          0
dtype: int64

In [ ]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
dtype: bool

In [ ]:
print(df.duplicated().sum())

0

In [ ]:
print(df['team_name'])

0     Royal Challengers Bangalore
1             Sunrisers Hyderabad
2                  Mumbai Indians
3          Rising Pune Supergiant
4                   Gujarat Lions
5           Kolkata Knight Riders
6             Chennai Super Kings
7                Rajasthan Royals
8                  Delhi Capitals
9                    Punjab Kings
10           Lucknow Super Giants
11                 Gujarat Titans
12                Deccan Chargers
13           Kochi Tuskers Kerala
14                  Pune Warriors
15        Rising Pune Supergiants
Name: team_name, dtype: str

In [ ]:
# ==========================
# Data 4 Player_Data = "players-data-updated.xlsx"
# ==========================

df = pd.read_excel(Player_Data)
df.head()

,player_id,player_name,bat_style,bowl_style,field_pos,player_full_name,player_name2,player_image
0,1,CH Gayle,Left hand Bat,Right arm Offbreak,,Christopher Henry Gayle,Christopher Henry,https://ipl-stats-sports-mechanic.s3.ap-south-...
1,2,Mandeep Singh,Right hand Bat,Right arm Medium,,Mandeep Singh,Mandeep Singh,NaN
2,3,TM Head,Left hand Bat,Right arm Offbreak,Wicketkeeper,Travis Michael Head,Travis Michael,https://ipl-stats-sports-mechanic.s3.ap-south-...
3,4,KM Jadhav,Right hand Bat,Right arm Offbreak,,Kedar Mahadav Jadhav,Kedar Mahadav,NaN
4,5,SR Watson,Right hand Bat,Right arm Fast medium,,Shane Robert Watson,Shane Robert,NaN

In [ ]:
df.tail()

,player_id,player_name,bat_style,bowl_style,field_pos,player_full_name,player_name2,player_image
767,43649,Harsh Dubey,Left hand Bat,Slow Left arm Orthodox,NaN,Harsh Surendra Dubey,Harsh Surendra,NaN
768,43820,MP Breetzke,Right hand Bat,NaN,Wicketkeeper,Matthew Paul Breetzke,Matthew Paul,NaN
769,43849,Musheer Khan,Right hand Bat,Slow Left arm Orthodox,NaN,Musheer Khan,Musheer Khan,https://www.espncricinfo.com/cricketers/mushee...
770,43881,BKG Mendis,Right hand Bat,Legbreak,NaN,Kusal Mendis,Kusal Mendis,NaN
771,43954,Sediqullah Atal,Left hand Bat,NaN,NaN,Sediqullah Atal,Sediqullah Atal,NaN

In [ ]:
df.shape

(772, 8)

In [ ]:
df.columns

Index(['player_id', 'player_name', 'bat_style', 'bowl_style', 'field_pos',
       'player_full_name', 'player_name2', 'player_image'],
      dtype='str')

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 772 entries, 0 to 771
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         772 non-null    int64
 1   player_name       772 non-null    str
 2   bat_style         772 non-null    str
 3   bowl_style        759 non-null    str
 4   field_pos         707 non-null    str
 5   player_full_name  772 non-null    str
 6   player_name2      772 non-null    str
 7   player_image      134 non-null    str
dtypes: int64(1), str(7)
memory usage: 27.2 KB

In [ ]:
df.describe()

          player_id
count    772.000000
mean   11085.305699
std    11339.197705
min        1.000000
25%     2016.750000
50%     9516.000000
75%    13385.000000
max    43954.000000

In [ ]:
df.isnull()

,player_id,player_name,bat_style,bowl_style,field_pos,player_full_name,player_name2,player_image
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...
767,False,False,False,False,True,False,False,True
768,False,False,False,True,False,False,False,True
769,False,False,False,False,True,False,False,False
770,False,False,False,False,True,False,False,True
771,False,False,False,True,True,False,False,True

In [ ]:
df.isnull().sum()

player_id             0
player_name           0
bat_style             0
bowl_style           13
field_pos            65
player_full_name      0
player_name2          0
player_image        638
dtype: int64

In [ ]:
df.fillna('NA')

,player_id,player_name,bat_style,bowl_style,field_pos,player_full_name,player_name2,player_image
0,1,CH Gayle,Left hand Bat,Right arm Offbreak,,Christopher Henry Gayle,Christopher Henry,https://ipl-stats-sports-mechanic.s3.ap-south-...
1,2,Mandeep Singh,Right hand Bat,Right arm Medium,,Mandeep Singh,Mandeep Singh,NA
2,3,TM Head,Left hand Bat,Right arm Offbreak,Wicketkeeper,Travis Michael Head,Travis Michael,https://ipl-stats-sports-mechanic.s3.ap-south-...
3,4,KM Jadhav,Right hand Bat,Right arm Offbreak,,Kedar Mahadav Jadhav,Kedar Mahadav,NA
4,5,SR Watson,Right hand Bat,Right arm Fast medium,,Shane Robert Watson,Shane Robert,NA
...,...,...,...,...,...,...,...,...
767,43649,Harsh Dubey,Left hand Bat,Slow Left arm Orthodox,NA,Harsh Surendra Dubey,Harsh Surendra,NA
768,43820,MP Breetzke,Right hand Bat,NA,Wicketkeeper,Matthew Paul Breetzke,Matthew Paul,NA
769,43849,Musheer Khan,Right hand Bat,Slow Left arm Orthodox,NA,Musheer Khan,Musheer Khan,https://www.espncricinfo.com/cricketers/mushee...
770,43881,BKG Mendis,Right hand Bat,Legbreak,NA,Kusal Mendis,Kusal Mendis,NA
771,43954,Sediqullah Atal,Left hand Bat,NA,NA,Sediqullah Atal,Sediqullah Atal,NA

In [ ]:
df.isnull().sum()

player_id             0
player_name           0
bat_style             0
bowl_style           13
field_pos            65
player_full_name      0
player_name2          0
player_image        638
dtype: int64

In [ ]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
767    False
768    False
769    False
770    False
771    False
Length: 772, dtype: bool

In [ ]:
print(df.duplicated().sum())

0